apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: dubbogo-adaptivesvc
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbogo-zookeeper-deployment
  name: dubbogo-zookeeper-deployment
  namespace: dubbogo-adaptivesvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper
          ports:
            - containerPort: 2181
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
