apiVersion: batch/v1
kind: Job
metadata:
  name: dubbogo-client
  namespace: dubbogo-adaptivesvc
spec:
  template:
    spec:
      containers:
        - name: dubbogo-client
          image: laurencelizhixin/dubbogo-client-adasvc:0.0.1
          env:
            - name: PARALLEL
              value: "10"
            - name: TPS
              value: "1"
      restartPolicy: Never
  backoffLimit: 4
